#!/bin/sh

NAME=MODULE_NAME
VERSION=MODULE_VERSION

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		moddir="/lib/modules/`uname -r`/kernel/"
      depmod
      if [ -d "/usr/src/$NAME-$VERSION" ]; then
         echo "Removing old module source..."
         rm -rf "/usr/src/$NAME-$VERSION"
      fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

