#!/bin/sh
# Copyright (C) 2002-2005 Flavio Stanchina
# Copyright (C) 2005-2006 Aric Cyr
# Copyright (C) 2007 Mario Limonciello
# Copyright (C) 2009 Alberto Milone

NAME=MODULE_NAME
PACKAGE_NAME=$NAME-dkms
CVERSION=`dpkg-query -W -f='${Version}' $PACKAGE_NAME | awk -F "-" '{print $1}' | cut -d\: -f2`

ARCH=`dpkg --print-architecture`
case $ARCH in
	amd64)
		ARCH="x86_64"
                ;;
	lpia)
		ARCH="i686"
		;;
	i386)
		ARCH="i686"
		;;
	*)
		echo "WARNING: unsupported arch: $ARCH"
		ARCH="$ARCH"
		;;
esac

case "$1" in
	configure)
		for POSTINST in /usr/lib/dkms/common.postinst /usr/share/$PACKAGE_NAME/postinst; do
			if [ -f $POSTINST ]; then
				$POSTINST $NAME $CVERSION /usr/share/$PACKAGE_NAME $ARCH $2
				exit $?
			fi
			echo "WARNING: $POSTINST does not exist."
		done
		echo "ERROR: DKMS version is too old and $PACKAGE_NAME was not"
		echo "built with legacy DKMS support."
		echo "You must either rebuild $PACKAGE_NAME with legacy postinst"
		echo "support or upgrade DKMS to a more current version."
		exit 1
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#
